---
title: "Research Projects"
---

**Peer-Reviewed Publications**

3\. Berny, L. M., **Guha, A.**, & Tanner-Smith, E. E. (2026). Distinguishing a drug use disorder from drug use in a high-risk sample of youth: A random forest classification and explanatory model analysis. *Drug and Alcohol Dependence Reports, 18,* Article 100412. <https://doi.org/10.1016/j.dadr.2026.100412>

2\. Sanchez, J. P., Zvoch, K., & **Guha, A.** (2025). Snap Judgments: Vulnerable decision points and subjective discipline incident referrals for Latinx students. *Journal of Latinos in Education, 24*(2), 453-466. <https://doi.org/10.1080/15348431.2024.2388628>

Open access version: [here](media/docs/sanchez_2025.pdf).

1\. McCuddy, T., Clark, M., **Guha, A.**, & McLeod, E. M. (2024). A longitudinal examination of gun reporting by middle and high-school students. *Journal of School Violence, 23*(4), 555-569. <https://doi.org/10.1080/15388220.2024.2356562>

Open access version: [here](media/docs/mccuddy_2024.pdf).

**Manuscripts Under Review or In-Preparation**

3\. Zvoch, K., **Guha, A.**, & Loan, C. M. (under review). Student success teams and on-track to graduation status in Oregon: An interrupted time series analysis.

2\. **Guha, A.,** Avelar, J., & Zvoch, K. (in preparation). Beyond Single-Axis Analysis: Applying the Intersectional MAIHDA Method to Examine Disparities in Subjective Disciplinary Incidents.

1\. **Guha, A.** (in preparation). *What matters for whom? Unpacking intersectionality, wellbeing, and retention in higher education* (Doctoral dissertation). University of Oregon.

**Policy Briefs**

6\. **Guha, A.**, Loan, C. M, Scalise, K., & Zvoch, K. (2023, September). *DYK #6: Student Success Teams and 9G-OTG Outcomes During the COVID-19 Pandemic.* Oregon Department of Education, Salem, OR.

5\. **Guha, A.**, Loan, C. M, Scalise, K., & Zvoch, K. (2023, September). *DYK #5: What Measure 98 Means for You.* Oregon Department of Education, Salem, OR.

4\. **Guha, A.**, Loan, C. M, Scalise, K., & Zvoch, K. (2023, September). *DYK #4: Student Success Teams and 9G-OTG outcomes prior to the COVID-19 Pandemic.* Oregon Department of Education, Salem, OR.

3\. **Guha, A.**, Loan, C. M, Scalise, K., & Zvoch, K. (2023, September). *DYK #3: The Ninth Grade On-Tack to Graduation (9G-OTG) Metric in Oregon.* Oregon Department of Education, Salem, OR.

2\. **Guha, A.**, Loan, C. M, Scalise, K., & Zvoch, K. (2022, September). *DYK #2: Measure 98 Student Success Team Implementation.* Oregon Department of Education, Salem, OR.

1\. **Guha, A.**, Loan, C. M, Scalise, K., & Zvoch, K. (2022, September). *DYK #1: What is Measure 98?* Oregon Department of Education, Salem, OR.

**CONFERENCE PRESENTATIONS**

11\. **Guha, A.** (2026, April 7-12). *An Intersectional Multilevel Analysis of Individual Heterogeneity and Discriminatory Accuracy (I-MAIHDA): Uncovering Sociodemographic Inequity in Wellbeing and Retention* \[Paper presentation\]. American Educational Research Association. Los Angeles, CA, United States.

10\. **Guha, A.** (2025, November 13-15). *Targeting What Matters Early: Using Machine Learning to Identify Malleable Predictors of First-Term GPA* \[Paper presentation\]. Association for Public Policy Analysis and Management. Seattle, WA, United States.

9\. **Guha, A.,** Avelar, J., & Zvoch, K. (2025, October 8-11). *Beyond Single-Axis Analysis: Applying the Intersectional MAIHDA Method to Examine Disparities in Subjective Disciplinary Incidents* \[Paper presentation\]. Society for Research on Educational Effectiveness. Chicago, IL, United States.

8\. Williams, K., **Guha, A.**, Chen, D., & Abrhale, A. (2025, June 23-26). *Enrollment Landscapes: Mapping the Institutional Factors Behind Enrollment Shifts*. NCES Data Institute, Washington, D.C., United States.

7\. Berny, L., **Guha, A.**, Avelar, J., Bates, E., & Schwear-Collins, M. (2025, May 27-30*). Prevalence of Electronic Nicotine Delivery Systems (ENDS) Use in U.S. Adults: A Design-Weighted MAIHDA* \[Paper presentation\]. Society for Prevention Research. Seattle, WA, United States.

6\. **Guha, A.**, Zvoch, K., & Loan, C. M. (2024, September 18-21). *Student Success Teams and On-Track to Graduation Status in Oregon: An Interrupted Time Series Analysis* \[Poster presentation\]. Society for Research on Educational Effectiveness. Baltimore, MD, United States.

5\. Zvoch, K., Loan, C., Scalise, K., & **Guha, A.** (2024, April 11-14). *Student Success Teams and On-Track to Graduation Status in Oregon: An Interrupted Time Series Analysis* \[Paper presentation\]. American Educational Research Association. Philadelphia, PA, United States.

4\. **Guha, A.** & Clark, B. (2023, September 27-30). *Envisioning the pathway to success: Effect of the Pathway Oregon scholarship on first-year outcomes* \[Poster presentation\]. Society for Research on Educational Effectiveness. Washington, D.C., United States.

3\. Scalise, K., Zvoch, K., Loan, C. M., **Guha, A**., & Farley, D. (2023, August). *A study in equity: Oregon's ninth grade transition. \[Paper presentation\]. NCES STATS-DC Data Conference. Washington, D.C., United States.*

2\. **Guha, A.** & Zhang, C. (2023, March 23-25). *Investigating the causal impact of teacher gender match on student learning* \[Paper presentation\]. American Education Finance and Policy. Denver, CO, United States.

1\. **Guha, A.**  & Loan, C. (2023, February 15). *Tracking High School Success: A Comparative Interrupted Time Series Analysis of Oregon’s Measure 98* \[Poster presentation\]. Graduate Research Forum. Eugene, OR, United States.
