---
title: "Teaching, Grants, & Awards"
format: html
---

## **Teaching Experience**

### **University of Oregon – Eugene, OR (Sep. 2020 – Present)**

#### Leadership 

• Education Policy and Leadership Master’s Program Director (Summers 2024, 2025)

• Graduate Teaching Fellow (Fall 2023 – Spring 2024)

#### Instructor of Record 

• EDUC 612: Social Science Research Design (Summers 2022, 2023, 2024, 2025)

• EDLD 211: Exploring Leadership (Fall 2021)

#### Teaching Assistant 

• EDUC 644: Applied Multivariate Statistics (Winter 2023)

• EDUC 642: Multiple Regression (Fall 2022)

• EDUC 640: Introduction to Data Science in Social Science (Spring 2022)

• EDUC 614: Educational Statistics (Winter 2022)

• EDLD 311: Equity, Leadership, and Social Change (Winter 2021)

• EDLD 211: Exploring Leadership (Fall 2020)

### **Teach for America – St. Louis, MO** 

Teaching Mentor (Aug. 2020 – May 2021)

• Classes: Algebra 1 and AP Statistics

### **Carnahan High School of the Future – St. Louis, MO** 

Secondary Mathematics Teacher (Aug. 2018 – May 2020)

• Classes: Algebra 1; Algebra II with trigonometry; ACT Prep; and Statistics

## **Grants and Awards**

+------------------+-----------------------------------------------------------------------+
| 2026             | University of Oregon – Eugene, OR                                     |
|                  |                                                                       |
|                  | **Doctoral Dissertation Award** (\$2,989)                             |
+------------------+-----------------------------------------------------------------------+
| 2025             | Association for Public Policy Analysis and Management – Seattle, WA   |
|                  |                                                                       |
|                  | **APPAM Fellowship** (\$1,000+)                                       |
+------------------+-----------------------------------------------------------------------+
| 2025             | Society of Research on Educational Effectiveness – Chicago, IL        |
|                  |                                                                       |
|                  | **Travel Award** (\$750)                                              |
+------------------+-----------------------------------------------------------------------+
| 2025 – 2026      | University of Oregon – Eugene, OR                                     |
|                  |                                                                       |
|                  | **Clare Wilkins Chamberlin Award** (\$3,000)                          |
+------------------+-----------------------------------------------------------------------+
| 2025             | University of Oregon – Eugene, OR                                     |
|                  |                                                                       |
|                  | **Graduate Division Award** (\$2,000)                                 |
+------------------+-----------------------------------------------------------------------+
| 2024 – 2026      | University of Oregon – Eugene, OR                                     |
|                  |                                                                       |
|                  | **David Moursund Scholarship Award** (\$10,400 scholarship recipient) |
+------------------+-----------------------------------------------------------------------+
| 2023, 2024       | Society of Research on Educational Effectiveness – Washington, D.C.   |
|                  |                                                                       |
|                  | **Researchers of Color Mentored Award** (\$1,200+/year)               |
+------------------+-----------------------------------------------------------------------+
| 2022 – 2023      | University of Oregon, Onward Eugene – Eugene, OR                      |
|                  |                                                                       |
|                  | **Women’s Innovation Network** (\$2,000)                              |
+------------------+-----------------------------------------------------------------------+
| 2020 – 2022      | University of Oregon – Eugene, OR                                     |
|                  |                                                                       |
|                  | **Promise Scholar** (\$6,000)                                         |
+------------------+-----------------------------------------------------------------------+
